### ISSUE TITLE
Add tests for replacing an object with null

### ISSUE THREAD

**Issue by jmeas** [Starcounter-Jack/Fast-JSON-Patch#62]
#35 was merged w.o. tests

**Comment by warpech** [comment]
Because it was submitted without tests. I added my own tests in the following commit so it should be good to go. Thanks!

**Comment by jmeas** [comment]
:+1: Nice

**Comment by winduptoy** [comment]
@jmeas Wait a minute... I'm on 0.5.1, but when I call
`[ { op: 'replace', path: '/foo', value: 'whatever' } ]`
on
`{foo: null}`
I get the error: "Cannot perform the operation at a path that does not exist".

Is this issue talking about the same thing, or just objects?

**Comment by jmeas** [comment]
Dunno, I stopped using this lib

**Comment by winduptoy** [comment]
@jmeas Any recommendations on a better one? Development has really slowed down on this one.

**Comment by jmeas** [comment]
I wound up realizing a JS object differ (rather than JSON) better suited my needs. I don't know of a better JSON object differ.

**Comment by tomalec** [comment]
#69 is fixed.
For tests I've created PR to https://github.com/json-patch/json-patch-tests/pull/17 Once it will get merged I'll pull it our test suite.
Is there any other case that you would to cover?
